trigger:
- master
- release/*

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: PR_FastCheck
    jobDisplayName: Fast Check
    agentOs: Windows
    buildArgs: "/p:FastCheck"
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build: Windows"
    agentOs: Windows
- template: jobs/iisintegration-job.yml
  parameters:
    variables:
      _FolderName: IISIntegration
