trigger:
- master
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/release/2.1

phases:
- template: .vsts-pipelines/templates/project-ci.yml@buildtools
  parameters:
    buildArgs: "/t:FastCheck"
- phase: RepoBuilds
  queue:
    name: Hosted VS2017
    parallel: 2
    matrix:
      DataProtection:
        _FolderName: DataProtection
      WebSockets:
        _FolderName: WebSockets
  steps:
  - script: src/$(_FolderName)/build.cmd -ci
    displayName: Run src/$(_FolderName)/build.cmd
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunner: vstest
      testResultsFiles: 'src/$(_FolderName)/artifacts/logs/**/*.trx'
