# We only want to run full helix matrix on master
# pr: none
trigger: none
schedules:
- cron: "0 */12 * * *"
  branches:
    include:
    - master
  always: true

# Remove this later
# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'
    
variables:
- ${{ if ne(variables['System.TeamProject'], 'internal') }}:
  - name: _UseHelixOpenQueues
    value: 'true'
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access
  - name: _UseHelixOpenQueues
    value: 'false'

# Helix ARM64
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_matrix_arm64
    jobDisplayName: "Tests: Helix ARM64 matrix"
    agentOs: Linux
    timeoutInMinutes: 480
    steps:
    - script: ./restore.sh -ci -nobl
      displayName: Restore
    - script: ./build.sh --ci --nobl --noBuildRepoTasks --arch arm64 -test --no-build-nodejs --all --projects
              $(Build.SourcesDirectory)/eng/helix/helix.proj /p:IsHelixJob=true /p:IsHelixDaily=true
              /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log
      displayName: Run build.sh helix arm64 target
      env:
        HelixApiAccessToken: $(HelixApiAccessToken) # Needed for internal queues
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    installNodeJs: false
    artifacts:
    - name: Helix_arm64_logs
      path: artifacts/log/
      publishOnError: true
      includeForks: true
