language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install nginx; brew install openssl; brew link --force openssl; else ./install-nginx.sh; fi
install:
  - export PATH="$PATH:$HOME/nginxinstall/sbin/"
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh --quiet verify

