init:
  - git config --global core.autocrlf true
install:
   # .NET Core SDK binaries
   # Download .NET Core SDK and add to PATH
   - ps: $urlCurrent = "https://go.microsoft.com/fwlink/?LinkID=834991"
   - ps: $urlPreview = "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip"
   - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
   - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
   - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
   - ps: $tempFilePreview = [System.IO.Path]::GetTempFileName()
   - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
   - ps: (New-Object System.Net.WebClient).DownloadFile($urlPreview, $tempFilePreview)
   - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
   - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFilePreview, $env:DOTNET_INSTALL_DIR + "preview")
   - ps: Copy-Item "${env:DOTNET_INSTALL_DIR}preview\*" "${env:DOTNET_INSTALL_DIR}" -Force -Recurse
   - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
build_script:
  - npm install -g npm@^3.0.0
  - npm --prefix templates/package-builder install
  - npm --prefix templates/package-builder run build
#  - build.cmd verify
clone_depth: 1
test_script:
  - dotnet restore ./src
  - npm install -g selenium-standalone
  - selenium-standalone install
  # The nosys flag is needed for selenium to work on Appveyor
  - ps: Start-Process selenium-standalone 'start','--','-Djna.nosys=true'
  - npm --prefix test install
  - npm --prefix test test
on_finish :
  # After running tests, upload results to Appveyor
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\tmp\junit\*.xml))
deploy: off
