trigger:
- master
- release/*

resources:
  repositories:
  - repository: buildtools
    type: git
    name: aspnet-BuildTools
    ref: refs/heads/master

phases:
- template: ../templates/server-tests-steps.yml
